### ISSUE TITLE
Building my first unit, several questions.

### ISSUE THREAD

**Issue by dabonetn** [profdc9/Apple2Card#2]
Need clarification on some things.

I've got my boards and I've got one nearly built up, and have a few questions.

1. Programming the atmega328p. You say "It should be flashed onto the ATMEGA328P chip without a bootloader. " but the bin file from the audrino output has the name Apple2Arduino.ino.with_bootloader.bin.. Should I just use the hex file named Apple2Arduino.ino.hex??
2. JP2, JP3, JP4 - Should only one of these be selected? What are they actually doing?
3. What jumpers are REQUIRED to run the unit? On the picture I see JP2, JP5 and JP7.
4. What do JP6, JP7, JP8, JP9 and JP10 do? Some seem to control ROM decoding.
5. What are the functions of the LEDs? I think I know, but documentation would be good.
6. Where are the setting stored? On the atmega or the eeprom? (U9)

Thanks!, I'll post more after I get it running over on the vcfed forum. 
Keep up the good work.

**Comment by profdc9** [comment]
Ok, a number of changes.  I recently revised the board to add some more
functionality.

1.  Program the bootloader first using a programmer.  This sets some fuses
in the ATMEGA328P.  Compile the latest arduino firmware off the project and
upload it using a programmer.  You may need to close JP1 when programming
to power the ATMEGA328P with the programmer if the board is not inside an
apple II when programming.  Make sure there are no SD cards in the slots
whe programming.
2.  The jumpers have changed.  Close jumpers
JP6,JP4,JP7,JP3,JP2,JP9,JP8,JP10.  Then use the "FLASH.SYSTEM" in the
project to flash the firmware onto the FLASH chip.  Then remove the jumpers
except for JP2.  It says this in the "FLASH.SYSTEM" program.
3.  The settings for which drives you are currently using are stored in the
ATMEGA328P EEPROM.  The ROM that the apple ][ sees to boot up is stored in
FLASH rom.
4.  The LEDs are basically convenient access lights to see when the cards
are accessing.  There are two for each card and a third for the planned
network support (W5500).

Dan

**Comment by dabonetn** [comment]
Is it possible to just program the atmega in the programmer? I've got a tl866 that can handle the chip directly without having to make a programming cable.
I'm also trying to use some standard eproms instead of the eeproms (Out of stock). So what offset does the firmware need to be in the physical chip please. (I have about a 100 27c512s....)

**Comment by profdc9** [comment]
You can program the atmega in the programmer but you must set the fuse
values to the standard Arduino fuse values as well as program the firmware.

You can use a 27C512 I believe, as the pinout should be compatible as long
as all the jumpers are open except JP2.  The firmware would be loaded
starting at location zero.

Dan

**Comment by profdc9** [comment]
The following may be useful to you to use the TL866II to set the right
fuses:

https://www.dmcmillan.co.uk/blog/burning-the-arduino-bootloader-to-an-atmega328-with-a-tl866ii
https://diychris.com/index.php/2020/05/13/burning-the-arduino-bootloader-using-the-tl866-ii-plus/

**Comment by profdc9** [comment]
Oops, it looks like on the 28C256 the WE line is pin A14 on the 27C512, so
for A14=1, the location to load the firmware at would be $4000, not $0.

Dan

**Comment by dabonetn** [comment]
Ok, I've got it showing to the apple (Getting the "DAN II PRESS RTN"  prompt).
Using a 8GB generic card that came with one of my 3d printers in slot 2, formatted fat32 and using disk images from www.apple-2.com converted to .po files using cider press, it always breaks to the monitor with

0803-      A=28 X=F8 Y=06 P=35 S=E4.

This is when I select a good disk image number or one that doesn't exist.
I'm slow formatting a 32gb card to try next.

When I tried writing a raw image out with cider press and selecting 0 for the boot, (Card is slot 1), the system just hangs.

**Comment by profdc9** [comment]
Format a card FAT32, and then put a 32 MB filesystem on it that is
"BLKDEV01.PO".  Put this card in the lower SD card slot (slot 1).  When you
are booting up, press enter, and then type "1" (for BLKDEV01.PO) for the
first slot, and then choose 0 for the second slot.  Try to see if that
works.

The location it tries to find the image on the card depends on the slot the
card is put into when in mode "0".  This is so many volumes can be accessed
with one card.  The location is at 32 MB X slot number for drive 1, and 32
MB X (slot number + 8) for drive 2.  32 MB = 33554432 bytes exactly.

If you can't get it right, copy the 32 MB file (33554432 byte) file
repeatedly onto the SD card starting at block 0 many times.   If you copy
it 16 times, it will be in all possible locations (all possible slots and
drives).

Dan

**Comment by profdc9** [comment]
I just tried the original image and the games image from that website, and
they seemed to work ok for e.

Dan

**Comment by dabonetn** [comment]
I was totally not getting the card 1 and 2 questions.... PLBKAC (Problem lies between keyboard and chair..)

I was trying just slot 2 for the fat32.. I thought slot one was raw sectors.

Just tried 4 of those images and they booted fine.. Total Replay crashes at boot, after displaying the Total Replay text.

Great job.

**Comment by profdc9** [comment]
That's weird. I can get Total Replay to work, but only if I boot from
another SD card first, for example, have a mode 0 SD card in slot 1, and
the Replay card in slot 2.

Either slot 1 or slot 2 can be raw sectors which is mode 0 or !  .   If it
is mode 0, the only the slot selected with mode 0 is raw sectors.  If it is
mode ! , both slots are raw sectors from the one SD card that is in SD card
slot 1.  It is possible to assign all of the drivers/sectors to the Dan ][
controller and get over 400 MB in 32 MB volumes.

Dan

**Comment by profdc9** [comment]
The easy way to do this is to write the Blankvols to a SD card and then
copy the files you want onto the card to make the bootable drive you want.
Blankvols contains 16 consecutive 32 MB filesystems.

Dan

**Comment by dabonetn** [comment]
""The easy way to do this is to write the Blankvols to a SD card and then
copy the files you want onto the card to make the bootable drive you want.
Blankvols contains 16 consecutive 32 MB filesystems.""

That's a little beyond me, I'm not very experienced with Prodos (Or Apple to be honest.) I was much more of a C64/IBM guy.
How do you boot the other file systems?

Maybe write up a how to? Like start with the most basic instructions and required files and programs?

**Comment by dabonetn** [comment]
Ok, another question.. Using both cards, I have images BLKDEV01.PO thtu BLKDEV08.PO files on each.

Booting I select 1 the 2 and boot into a image. (Lets say the booti image), Then if I go into Copy II Plus utils and do a Catalog on slot 7 drive 1, I see the booti drive that I mapped to slot 1, but slot 2 has a read error.

Powering down and swapping cards between the slots results in the same error.

I'm thinking that slot 2 isn't working correctly. Would enabling the debug serial port show any useful information for trouble shooting this? 

Thanks, I'm enjoying the learning with this one.

**Comment by profdc9** [comment]
Unfortunately, only one of the slots can use a FAT filesystem based image.
The other must be a 0 based image which is a direct block device. So if you
want to copy between volumes, you need to do it via a block 0 device.
Unfortunately, there is not enough RAM in the Arduino to keep track of two
filesystems.

Dan

**Comment by dabonetn** [comment]
That worked great, now if I only knew how to change partitions using straight prodos on a //e 64k..
Thanks!

**Comment by profdc9** [comment]
I'm not sure what you mean with how to change partitions.

It should be possible to change which volumes you are using between boots,
however, I haven't written the program to do that yet...

BTW, Total Replay doesn't seem to have a PRODOS file on it so I don't think
it's bootable in the conventional way.

Dan

**Comment by dabonetn** [comment]
"" It is possible to assign all of the drivers/sectors to the Dan ][
controller and get over 400 MB in 32 MB volumes""

Ok, by partitions, I meant volumes.. (Sorry, PC guy here..).

"" If ! is pressed, then the mode is wide block mode where both drive 1 and drive 2 of ProDOS are directed to SLOT 1.""

Can you define WIDE block mode better? I used the base BlankVols.po image and put an image in each volume with ciderpress.

**Comment by profdc9** [comment]
Ok, so I don't have code to do this yet, but at memory addresses
$BF00-$BFFF (somewhere in there) are the addresses of the driver for each
slot and drive number.  If you choose "0" or "!" and you point the slot and
drive to the driver on the Dan ][ controller, it will use the volume that
is at a given location on the SD card.  So for example, you may not have a
storage device in slot 2, but you could overwrite the address in the table
so that the slot 2 driver goes to the Dan ][ controller and you could get
up to 64 MB (two volumes of 32 MB each for the two drives at that slot)
additional storage.

Yes I know this is not all done yet but honestly even 64 MB is plenty for
most Apple ][ things so it hasn't been a high priority....

**Comment by dabonetn** [comment]
So I get that I hit ! for wide mode, but for the second question does it matter what you answer for that one?

I'm trying the following sd cards.
4gb
8gb
32gb.

I'm writing out the BlankVols.po image you provided, after I load the partitions.
It always boots the last partition. Either selecting 0 or !.
Selecting ! and a number with no card in slot 2 boots the last partition from the Blankvols.po, and when I hit tab, it lists 7,2
as NEW.DISK.

the 4gb and 8gb were written using Ciderpress.
The 32gb is written using windiskimager.

Doubling up the Blanksvols.po image and writing it to the 32gb still presents NEW.DISK.

**Comment by dabonetn** [comment]
Ok, another question for you.

In the wide block mode where both drive 1 and 2 are directed to slot one, where are the boundaries of drives 1 and 2?
I assume since it's block mode, drive 1 starts at sector 0, but how about drive 2?

How many block are presented to the apple when the card is running in block mode per drive?

Thanks.
(p.s. thanks for the quick Total Recall patch!)

**Comment by profdc9** [comment]
Sure, when the source of the problem was pointed out it was easy to fix.

The format on the SD card is that each 32 MB volume is a slot and drive, or
65535 blocks + 1 empty block.

The order of the volumes for the first 512 MB of a card:

S0D1 S1D1 S2D1 S3D1 S4D1 S5D1 S6D1 S7D1
S0D2 S1D2 S2D2 S3D2 S4D2 S5D2 S6D2 S7D2

So for example, for S4D2, this would be (11 X 65536 blocks) into the SD
card.

When a "0" mode is used for slot 1, it uses these volumes on the SD card in
slot 1:
S0D1 S1D1 S2D1 S3D1 S4D1 S5D1 S6D1 S7D1

When a "0" mode is used for slot 2, it uses these volumes on the SD card in
slot 2:
S0D2 S1D2 S2D2 S3D2 S4D2 S5D2 S6D2 S7D2

When "!" is used in slot 1, both of the ProDOS drives use slot 1.

**Comment by dabonetn** [comment]
Ok, I'm now that I'm seeing the layout it making more sense, (like why the S7D1 volume is always the one that boots with the card in slot 7).

But how exactly would you access any slot on the sdcard besides the one that the card is currently in?

I have a test image a test image I wrote out to the card, and I can see S1,S2,S4,S5,S6,and S7 both drives one and two on each, by physically moving the card to the slot number. 

This is on a ][e standard 6502, with 64k ram and a old style 80 column card.

I haven't dug out my //gs for testing yet.

**Comment by profdc9** [comment]
Well, I plan to make it so that you can copy the driver address to other
slots which don't already have any block devices addressed to them, and
this way you can use the card with many block devices.  I haven't written
the program to do this automatically yet but I have manually tested it.

Dan

**Comment by dabonetn** [comment]
Ah, ok.

**Comment by dabonetn** [comment]
Since all my questions have been answered, I'm closing this.

**Comment by profdc9** [comment]
More to the point.... if you look at addresses $BF10-$BF2F in Prodos,
that's where the addresses of the device drivers are.  If you change them
to match the device driver address for the Dan ][, and you have written the
BlankVols.po to the card, it should use the appropriate volume on the card
for the slot and drive.

Dan

**Comment by profdc9** [comment]
In wide mode,

slot 0 drive 2 starts at sector 8 X 65536 = 524288
slot 1 drive 2 starts at sector 9 X 65536 = 589824
etc...
