### ISSUE TITLE
Compatibility with Total Replay

### ISSUE THREAD

**Issue by frankmilliron** [profdc9/Apple2Card#3]
Hello. We have had a report that the card does not work with Total Replay. Looking at the code I'm seeing a conflict with memory locations $00FE and $00FF which are used for storage by both the card, as well as TR's "proboot" bootloader. One location is used for a 'knownRTS'. Not sure if you know, but the Apple ][ ROM already has a known RTS at location $FF58. Perhaps the other variable can be moved to another location in zero page which also doesn't conflict with ProDOS? ($FD perhaps? proboot only uses $FE and $FF) Also, TR will boot normally if copied to a standard ProDOS partition and the 'PRODOS' binary is included. It can also boot from the second drive if 'LAUNCHER.SYSTEM' is selected in Bitsy Bye. Anyway, fun project and hopefully we can help you get TR running natively on it! Frank

**Comment by profdc9** [comment]
$FF58 is not available when the language card memory is activated.  I could
change the locations fairly easily if that would help and not conflict with
other zero page usage.  I think I could also eliminate the use of one
location.  How about $FD?

**Comment by profdc9** [comment]
I just changed the firmware to use $FD only.  I tested it with Total Replay
and so far so good.  You can use FLASH.SYSTEM to reflash your card.

**Comment by frankmilliron** [comment]
That's great. I'll close the issue in Total Replay and let 'dabonetn' know! Thanks
